### ISSUE TITLE
Transforms for each color transformation

### ISSUE THREAD

**Issue by jorge-pessoa** [jorge-pessoa/pytorch-colors#1]
To simplify the usage of color transforms in the PyTorch pipeline, a Generic Transform and transforms for each of the color transformations should be provided.

**Comment by htoyryla** [comment]
I tried use the hsv transforms in gan training (i.e. training a generator to operate in HSV color space instead of RGB), but was getting huge out-of-range values. 

It turned out that the problem was the RGB values being in the -1 .. 1 range after the normalization typical of gan training. Scaling to 0 .. 1 for the rgb_to_hsv transform and the back to -1 .. 1 helped, but I think the idea of pytorch specific color transforms is to avoid such tricks. 

Having normalize and range options similar to transforms.vutils could, I think, also be useful.

**Comment by jorge-pessoa** [comment]
Thank you very much for the feedback. I haven't had much time to upgrade this utility but I'll take a look at your suggestions. Those seem simple enough and worthwhile. I'll let you know once they're available for testing

**Comment by jorge-pessoa** [comment]
In the meanwhile, this issue is outdated. If there is a particular suggestion you have other than the previously mentioned improvements, feel free to open a new issue. I'll close this one to avoid confusion
